### ISSUE TITLE
Localtunnel is experiencing stability issues

### ISSUE THREAD

**Issue by pyr0gan** [figment-networks/figment-apis-demo-app#3]
Unfortunately, usage of this app is impacted by ongoing stability issues with Localtunnel.

See https://github.com/localtunnel/localtunnel/issues/560 for details.

**Comment by yash-sharma1** [comment]
Thanks for opening the issue, Rogan! As soon as localtunnel gets fixed we can try again testing the app.

**Comment by pyr0gan** [comment]
Updated both branches with a comment about launching the tunnel and links to the localtunnel repo & issues -> https://github.com/figment-networks/figment-apis-demo-app/commits/main
